version: "3"

services:
  optimaze-graph:
    container_name: graph2
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"